### ISSUE TITLE
Using this driver in a C++ appliction.

### ISSUE THREAD

**Issue by markospacetech** [adafruit/Adafruit_CircuitPython_RockBlock#24]
Hello all,

I am looking to interface with my rockBLOCK 9603 + RPI B3 in a C++ application/framework, namely NASA's [fprime](https://github.com/nasa/fprime) framework.

The two options I can see now are
1. Embed the python libraries into my code (understanding the performance costs) to finish a prototype faster (hopefully), with a plan to most likely write a c++ driver in the future
2.  Invest the time to recreate this driver as a c++ driver now.

I come here to see if anyone has experience using these drivers with C++ or can give some feedback/better approach to solving this task.

Cheers

**Comment by caternuson** [comment]
Found this by just searching, looks like it hasn't been touch in years. But may be useful?
https://github.com/mikalhart/IridiumSBD

**Comment by markospacetech** [comment]
Just took a look at that as well, tried using it on my RPI as well but its highly coupled with Arduino libraries. Maybe with [RaspiArduino](https://github.com/me-no-dev/RasPiArduino) I could upload a sketch and call it from the C++ app. Although, since it hasn't been maintained for so long I'm leaning towards embedded python.

**Comment by caternuson** [comment]
Sounds like you're wanting something more bare bones, i.e. not Arduino. Like a bare C++ library. If so, yah, probably best to not use an Arduino library and try to force it in somehow. But not aware of any such C++ library out there for this. Adafruit libraries will either be CircuitPython/Python or Arduino.

Closing since this is not a code issue with this repo.
